### ISSUE TITLE
show_windows option not working

### ISSUE THREAD

**Issue by tf79** [Mri-monitoring/Mri-python-client#2]
I'm not sure if I should open an issue for each problem. Seems like right procedure, so please correct me if I'm wrong! 

'show_windows' is not working for me. Setting true or false, either way a window gets open at the end of one training task and freezes. However, I noticed that the window name changed permanent to 'Figure 1'. So After 3 training tasks I have 3 frozen windows named Figure 1.

**Comment by nharada1** [comment]
Fixed in [Mri-app](https://github.com/Mri-monitoring/Mri-app/commit/f81047599a3fd85bd721f093ae1a0f4fe0915ff6)

Thanks! Keep em coming
